# Pytorch
python 기반의 과학 연산 패키지로 다음과 같은 두 집단을 대상으로 합니다.
* Numpy를 대체하면서 GPU를 이용한 연산이 필요한 경우.
* 최대한 유연성과 속도를 제공하는 딥러닝 연구 플랫폼이 필요한 경우.

# Tensors
Numpy의 ndarray와 유사하며, GPU를 사용한 연산 가속이 가능합니다.

In [2]:
from __future__ import print_function
import torch

초기화되지 않은 5x3 행렬을 생성합니다.

> 초기화되지 않은 행렬이 선언되었지만, 사용하기 전에는 명확히 알려진 값을 포함하고 있지는 않습니다. 초기화되지 않은 행렬이 생성되면 그 시점에 할당된 메모리에 존재하던 값들이 초기값으로 나타납니다.

In [3]:
x = torch.empty(5, 3)
print(x)

tensor([[-3.4229e-19,  4.5839e-41,  4.8794e-11],
        [ 3.0854e-41,  1.3556e-19,  1.8567e-01],
        [ 7.5553e+28,  5.2839e-11,  2.9396e+29],
        [ 1.2681e-14,  2.0319e-43,  0.0000e+00],
        [-3.4228e-19,  4.5839e-41, -3.4228e-19]])


무작위로 초기화된 행렬을 생성합니다.

In [4]:
x = torch.rand(5, 3)
print(x)

tensor([[0.5963, 0.9885, 0.3998],
        [0.8336, 0.9068, 0.7597],
        [0.6472, 0.3066, 0.2029],
        [0.0023, 0.1466, 0.0020],
        [0.5550, 0.3138, 0.8907]])


dtype이 long이고 0으로 채워진 행렬을 생성합니다.

In [5]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


데이터로부터 tensor를 직접 생성합니다.

In [7]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


기존 tensor을 바탕으로 새로운  tensor을 만듭니다. 이들 메소드(method)는 사용자로부터 새로운 값을 제공받지 않은 한, 입력 tensor의 속성들을 재사용합니다.

In [8]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [9]:
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[-0.8236,  0.2366,  1.3145],
        [-0.0413, -0.0112, -0.4685],
        [ 0.3668, -0.4564,  1.4305],
        [-1.1291, -0.1744, -0.1620],
        [ 0.6410,  0.1915, -0.5809]])


행렬의 크기를 구합니다

> `torch.size` 는 튜플(tuple) 타입으로, 모든 튜플 연산을 지원합니다.

In [10]:
print(x.size())

torch.Size([5, 3])


# 연산(Operations)

## 덧샘

In [11]:
y = torch.rand(5, 3)
print(x + y)

tensor([[-0.1196,  0.2630,  1.4959],
        [ 0.0112,  0.3705, -0.2613],
        [ 0.6006, -0.0819,  1.9354],
        [-0.5265,  0.1848,  0.0530],
        [ 1.4501,  0.9217, -0.1907]])


In [12]:
print(torch.add(x, y))

tensor([[-0.1196,  0.2630,  1.4959],
        [ 0.0112,  0.3705, -0.2613],
        [ 0.6006, -0.0819,  1.9354],
        [-0.5265,  0.1848,  0.0530],
        [ 1.4501,  0.9217, -0.1907]])


결과 Tensor를 인자로 제공

In [13]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-0.1196,  0.2630,  1.4959],
        [ 0.0112,  0.3705, -0.2613],
        [ 0.6006, -0.0819,  1.9354],
        [-0.5265,  0.1848,  0.0530],
        [ 1.4501,  0.9217, -0.1907]])


바꿔치기(`in-place`) 방식

> 바꿔치기(`in-place`) 방식으로 tensor의 값을 변경하는 연산 뒤에는 `_` 가 붇습니다.

> 예시: `x.copy(y)`, `x.t_()` 는 `x` 를 변경합니다. 

In [15]:
y.add_(x)
print(y)

tensor([[-0.9432,  0.4996,  2.8104],
        [-0.0301,  0.3593, -0.7298],
        [ 0.9674, -0.5383,  3.3659],
        [-1.6555,  0.0104, -0.1089],
        [ 2.0911,  1.1132, -0.7716]])


Numpy의 인덱싱 표기 방법을 사용할 수 있습니다.

In [17]:
print(x[:, 1])

tensor([ 0.2366, -0.0112, -0.4564, -0.1744,  0.1915])


## 크기 변경

tensor의 크기(size)나 모양(shape)을 변경하고 싶다면 `torch.view`를 사용합니다.

In [18]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)

print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


만약 tensor에 하나의 값만 존재한다면 `.item()` 을 사용하면 숫자 값을 얻을 수 있습니다.

In [19]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.5203])
-0.5202743411064148


# Numpy 변환

(Torch Tensor가 CPU 상에 있다면) Torch Tensor와 Numpy 배열은 메모리 공간을 공유하기 때문에, 하나를 변경하면 다른 하나도 변경됩니다.

## Torch Tensor를 Numpy 배열로 변환하기

In [20]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [21]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [22]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


## Numpy 배열을 Torch Tensor로 변환하기

In [25]:
import numpy as np

In [26]:
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


CharTensor를 제외한 CPU 상의 모든 Tensor는 Numpy로 변환할 수 있고, 반대 변환도 가능합니다.

# Cuda Tensor

`.to` 메소드를 사용하여 Tensor를 어떤 장치로도 욺길 수 있습니다.

In [27]:
# 이 코드는 CUDA가 사용가능한 환경에서만 실행됩니다.
# torch.device를 사용하여 tensor를 GPU에서 CPU로 이동합니다.
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y

    print(z)
    print(z.to("cpu", torch.double))

tensor([0.4797], device='cuda:0')
tensor([0.4797], dtype=torch.float64)
